cp build/test-renderer.js "$TEKVIDEO_HOME/grails-app/assets/javascripts/perseus/"
cp build/editor-perseus.js "$TEKVIDEO_HOME/grails-app/assets/javascripts/perseus/"
cp build/frame-perseus.js "$TEKVIDEO_HOME/grails-app/assets/javascripts/perseus/"
cp build/demo-perseus.js "$TEKVIDEO_HOME/grails-app/assets/javascripts/perseus/"
echo "Copied"
